[build]
  command = "CI='' npm run build"
  publish = "/build"
  base ="/wordle"
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"